name: NClaim
version: ${version}
main: nesoi.aysihuniks.nclaim.NClaim
api-version: '1.16'
authors: [ aysihuniks, yoshii01 ]
description: Advanced Chunk Claim System
depend: [PlaceholderAPI]
softdepend: [Vault, DecentHolograms, FancyHolograms, SkinRestorer, WorldGuard, Farmer, AxSellwands, SmartSpawner, EnhancedPets]
commands:
  nclaim:
    aliases: [ nc, claim ]
    usage: "/nclaim <help/?>"
permissions:
  nclaim.admin:
    default: false
    children:
      nclaim.adminmenu: true
      nclaim.reload: true
      nclaim.add: true
      nclaim.remove: true
      nclaim.change: true
      nclaim.set: true
  nclaim.*:
    default: op
    children:
      nclaim.admin: true
      nclaim.bypass.*: true
  nclaim.bypass.*:
    default: false
    children:
      nclaim.bypass.blacklisted_worlds: true
      nclaim.bypass.blacklisted_regions: true
      nclaim.bypass.max_claim_count: true
      nclaim.bypass.max_coop_count: true
      nclaim.bypass.claim_buy_price: true
      nclaim.bypass.land_buy_price: true
      nclaim.bypass.pvp: true
      nclaim.bypass.interact: true
      nclaim.bypass.break: true
      nclaim.bypass.place: true
      nclaim.bypass.axsellwand: true
  nclaim.use:
    default: true
    children:
      nclaim.help: true
      nclaim.balance: true
      nclaim.buy: true
      nclaim.level: true
      nclaim.maxcoop.default: true
  nclaim.help:
    default: false
  nclaim.maxcoop.default:
    default: false
  nclaim.balance:
    default: false
  nclaim.buy:
    default: false
  nclaim.level:
    default: false
  nclaim.manage_claim_block:
    default: false
  nclaim.adminmenu:
    default: false
  nclaim.reload:
    default: false
  nclaim.add:
    default: false
  nclaim.remove:
    default: false
  nclaim.set:
    default: false
  nclaim.change:
    default: false
  nclaim.bypass.blacklisted_worlds:
    default: false
  nclaim.bypass.blacklisted_regions:
    default: false
  nclaim.bypass.max_claim_count:
    default: false
  nclaim.bypass.max_coop_count:
    default: false
  nclaim.bypass.claim_buy_price:
    default: false
  nclaim.bypass.land_buy_price:
    default: false
  nclaim.bypass.pvp:
    default: false
  nclaim.bypass.interact:
    default: false
  nclaim.bypass.break:
    default: false
  nclaim.bypass.place:
    default: false
  nclaim.bypass.axsellwand:
    default: false
  nclaim.maxclaim:
    default: false